services:
  - type: web
    name: blog-builder-api
    env: node
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: web
    name: blog-builder-frontend
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run dev
    staticPublishPath: dist/public
    envVars:
      - key: NODE_ENV
        value: production